/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '7/5/16 3:22 PM' with Gradle 2.13
 *
 * @author sbyan, @date 7/5/16 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
